#let lang = "de"
#let region = "CH"
#let paper = "a4"
#let margin = (x: 2.5cm, y: 4.25cm)
#let font = ("source sans 3",)
#let fontsize = 11pt
#let pagenumbering = "1/1"
#let authors = ((name: [Andreas Burri], email: "", affiliation: ""),)
#let titlepage = false
#let titlepage-rule = 2.5pt + black
#let titlepage-bg = none
#let titlepage-fg = none
#let date = datetime.today().display("[day].[month].[year]")